name: Trigger for branch

run-name: ${{github.actor}}

on:
  push:
    branches:
      - master
    branches-ignore:
      - development
      
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "trigger the workflow for the branch"
    
      
