name: Trigger for branch

run-name: ${{github.actor}}

on:
  push:
    branches-ignore:
      - develop
      
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "trigger the workflow for the branch"
    
      
