name: Log and set workflow variables 

on:
  push:
    branches:
      - main
jobs:
  echo-context-variables:
    runs-on: ubuntu-latest
    steps: 
      - name: github context
        run: |
          echo "event name is ${{github.event_name}}"
          echo "Actor is ${{github.actor}}"
      - name: set user workflow variable 
        run: echo "user=${{github.actor}}" >> $GITHUB_ENV
      - name: Display variable
        run: echo "user variable is ${{env.USER}}"
