name: Deployment workflow

on: 
  push:
    branches: 
      - main
      - develop

jobs: 
  echo-deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set DEPLOY_ENV based on branch 
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          fi

      - name: Log DEPLOY_ENV
        run: echo "DEPLOY_ENV is set to ${{ env.DEPLOY_ENV }}"

      - name: Simulate deployment
        run: |
          echo "Deploying to ${{ env.DEPLOY_ENV }} environment"
          echo "Deployment Simulated for ${{ env.DEPLOY_ENV }}"
