name: Deployment workflow

on: 
  push:
    branches: 
      - main
      - develop
jobs: 
  echo-deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: Set DEPLOY_ENV based on branch 
        run: |
          if [["${github.ref} == "refs/hands/main" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          elif [[ "${github.ref}" == "refs/heads/develop" ]]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          fi
      - name: Log DEPLOY_ENV
        run: echo "DEPLOY_ENV is set to ${{env.DEPLOY_ENV}}"
      - name: Simulate deployment
        run: |
          echo "Deploying to ${DEPLOY_ENV} environment"
          echo "Deployment Simulated for $DEPLOY_ENV"








          
