name: events run with the filters & activity types

run-name: ${{github.actor}}

on:
  push:
    types:
      - opened
      - syncronised 
    branches:
      - master
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Run the job when PR opened and syncronised"

