name: expression

on: 
  push:
  workflow_dispatch:
    inputs: 
      debug: 
        type: boolean
        default: false
jobs: 
  echo-expression:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] print startup info'
        if: ${{inputs.debug}}
        run: |
          echo "triggered by ${{github.event_name}}"
          echo "branch is ${{github.ref}}"
      - name: '[debug] print when triggered from master'
        if: ${{inputs.debug && github.ref == 'refs/heads/master'}}
        run: echo 'I have triggered from master'
