name: Functions

on:
  push:
  workflow_dispatch:
    

jobs:
  echo-functions:
    runs-on: ubuntu-latest

    env:
      myString: Mona the Octocat
      myArray: '["apple", "banana", "cherry"]'
      myJSON: '{"name": "Octocat", "role": "Mascot"}'

    steps:
      - name: Check if String contains a substring
        run: |
          if ${{ contains(env.myString, 'Octocat') }}; then
            echo "The string contains 'Octocat'."
          else
            echo "The string does not contain 'Octocat'."
          fi

      - name: Check if String ends with a substring
        run: |
          if ${{ endswith(env.myString, 'Octocat') }}; then
            echo "The string ends with 'Octocat'."
          else
            echo "The string does not end with 'Octocat'."
          fi

      - name: Convert Array to JSON
        run: |
          json_str="${{ tojson(env.myArray) }}"
          echo "Converted array to JSON: $json_str"

      - name: Check if String starts with a substring
        run: |
          if ${{ startswith(env.myString, 'Mona') }}; then
            echo "The string starts with 'Mona'."
          else
            echo "The string does not start with 'Mona'."
          fi

      - name: Parse JSON from a String
        run: |
          json_obj="${{ fromjson(env.myJSON) }}"
          echo "Parsed JSON: $json_obj"
          echo "Name: ${{ fromjson(env.myJSON).name }}"
          echo "Role: ${{ fromjson(env.myJSON).role }}"
