name: github context
env:
  VAR: 'workflow'
on:
  push:
  workflow_dispatch:
jobs:
  echo-github-context:
    runs-on: ubuntu-latest
    env:
      VAR: 'Job'
    steps: 
      - name: Display information
        run: |
          echo "Action is ${{github.action}}"
          echo "Action path is ${{github.action_path}}"
          echo "Actor ref is ${{github.action_ref}}"
          echo "Actor Repository is ${{github.action_repository}}"
          echo "Actor Status is ${{github.action_status}}"
          echo "Actor ID is ${{github.actor_id}}"
          echo "Event name is ${{github.event_name}}"
          echo "Ref is ${{github.ref}}"
          echo "SHA is ${{github.SHA}}"
          echo "Actor is ${{github.actor}}"
          echo "Workflow is ${{github.workflow}}"
          echo "Run ID is ${{github.run_id}}"
          echo "Run Number is ${{github.run_number}}"
          echo "environment value is ${{env.VAR}}"
        env: 
          VAR: 'step'



          
  
