name: main reusable Workflow_call

on:
  push:
    branches:
      - main

jobs:
  trigger-reusable-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger from Workflow_call with Secrets
        uses: ./.github/workflows/workflow-call.yml
        with:
          param1: value1
          param2: value2
        secrets:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          MY_SECRET_KEY_1: ${{ secrets.MY_SECRET_KEY_1 }}
