name: Main CI/CD Workflow

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/reusable.yml
    with:
      test_suite: 'lint'

  unit-tests:
    uses: ./.github/workflows/reusable.yml
    with:
      test_suite: 'unit'

  integration-tests:
    uses: ./.github/workflows/reusable.yml
    with:
      test_suite: 'integration'
