name: matrix-include-exclude
on:
  workflow_dispatch:
jobs:
  matrix-include-exclude:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14, 16, 18]
  
        exclude:
          - os: windows-latest
            node: 14
          - os: macos-latest
            node: 18
  
        include:
          - os: ubuntu-latest
            node: 20
          - os: windows-latest
            node: 16
            extra-config: "special-setting"
  
    steps:
      - name: Print OS and Node.js version
        run: echo "Running on ${{ matrix.os }} with Node.js ${{ matrix.node }}"
        
