name: Fruits Filtering Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-filtering-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run Fruits Filtering Script
        run: |
          echo 'const fruits = [
            { "name": "apple", "quantity": 1 },
            { "name": "orange", "quantity": 2 },
            { "name": "pear", "quantity": 1 }
          ];' > filterFruits.js
          echo 'let selectedFruits = fruits.filter(fruit => fruit.quantity === 1);' >> filterFruits.js
          echo 'console.log("Selected Fruits: ", selectedFruits);' >> filterFruits.js
          node filterFruits.js
      - name: Verify Filtering Output
        run: |
          node filterFruits.js
