name: Sample workflow

run-name: ${{github.actor}}

on: 
  schedule:
    - cron: '* * * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "deploy the sameple workflow"
 








