name: secrets
on:
  workflow_dispatch:
jobs:
  echo-secrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Docker username is ${{secrets.DOCKER_NAME}}"
      - run: echo "Docker password is ${{secrets.DOCKER_PASSWORD}}"
