name: Self-hosted Runner
on:
  push:
    branches:
      - main
jobs:
  self-hosted:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print self hosted
        run: echo "this run from the Self-hosted Runner"
