name: Status Check Functions

on:
  push:
  workflow_dispatch: 

jobs:
  eco-status-check-functions:
    runs-on: ubuntu-latest

    env:
      userString: "Manikanta, DevOps"
      projectStatus: "In Progress"
      userJSON: '{"name": "Manikanta", "role": "DevOps", "department": "Tech", "location": "HCLTech"}'

    steps:
      - name: Set up the environment
        run: |
          echo "Setting up the environment"
        
      - name: Task-1
        run: |
          echo "Working on the task-1"
          echo "Task-1: Success"
          
      - name: Task-2
        run: |
          echo "Working on the task-2"
          exit 1 
        
      - name: Check if Task-1 was successful
        run: |
          if ${{ success() }}; then
            echo "Task-1 was successful."
          else
            echo "Task-1 failed."
        
      - name: Check if Task-2 was successful
        run: |
          if ${{ failure() }}; then
            echo "Task-2 failed as expected."
          else
            echo "Task-2 succeeded unexpectedly."
        
      - name: Always run this step
        run: |
          echo "This step always runs incase of success or failure."
        
      - name: Check workflow canceled
        run: |
          if ${{ canceled() }}; then
            echo "The workflow was canceled."
          else
            echo "The workflow was not canceled."
        
      - name: Final Status
        run: |
          echo "Final status: ${{ env.projectStatus }}"
          echo " output is: ${{ fromjson(env.userJSON).name }} - Role: ${{ fromjson(env.userJSON).role }}"

