name: reusable Workflow

on:
  workflow_call:
    inputs:
      param1:
        required: true
        type: string
      param2:
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display Parameters and Secrets
        run: |
          echo "Received param1: ${{ inputs.param1 }}"
          echo "Received param2: ${{ inputs.param2 }}"
          echo "MY_SECRET_KEY is available: ${{ secrets.MY_SECRET_KEY }}"
          echo "MY_SECRET_KEY_1 is available: ${{ secrets.MY_SECRET_KEY_1 }}"
